#pragma once

void InitItem();
void InitBundle();
void InitJewel();
void InitWing();
void ItemModelLoad();
void ItemTextureLoad();
void LoadItemModel(int index,char* folder,char* name);
void LoadItemTexture(int index,char* folder);
void GetItemColor(DWORD a,DWORD b,DWORD c,DWORD d,DWORD e);
void GetItemEffect(DWORD a,int b,float* c,float d,int e,int f,int g,int h,int i);
BOOL CheckSocketItem(DWORD address, DWORD this_pointer);
void ItemSocketName1();
void ItemSocketName2();
void ItemSocketName3();
void BundleCheckIndex1();
void BundleCheckIndex2();
void BundleCheckIndex3();
void BundleCheckIndex4();
void BundleCheckIndex5();
void JewelSetSalePrice();
void JewelCheckApplyItem();
void JewelCheckIndex1();
void JewelCheckIndex2();
void JewelCheckIndex3();
void JewelCheckIndex4();
void JewelCheckModelIndex1();
void JewelCheckModelIndex2();
void WingMakePreviewCharSet();
void WingDisableLevelGlow();
void WingSetIncDamage();
void WingSetDecDamage();
void WingSetDefense();
void WingSetExtraDefense();
void WingSetOption();
void WingSetNewOption();
void WingSetModelType();
void WingCheckIndex1();
void WingCheckIndex2();
void WingCheckIndex3();
void WingCheckIndex4();
void WingCheckIndex5();
void WingCheckIndex6();
void WingCheckIndex7();
void WingCheckIndex8();
void WingCheckIndex9();
void WingCheckIndex10();
void WingCheckIndex11();
void WingCheckIndex12();
void WingCheckIndex13();
void WingCheckIndex14();
void WingCheckIndex15();
void WingCheckIndex16();
void WingCheckIndex17();
void WingCheckIndex18();
void WingCheckIndex19();
void WingCheckIndex20();
void WingCheckIndex21();
void WingCheckIndex22();
void WingCheckIndex23();
void WingCheckModelIndex1();
void WingCheckModelIndex2();
void WingCheckModelIndex3();